### ISSUE TITLE
Temperature measurements

### ISSUE THREAD

**Issue by BaptisteVandecrux** [EnviDat/monitoring-backend#1] opened 2020-10-01 11:33 UTC
I see that there are only two temperature measurements in the output file. Are they from the thermocouples or from the CS500?
I suggest that all four air temperature measurements are being released.

Ionut:
> Sure, we can do that. Although not all GC-Net stations have four temperature measurements, my goal (for GC-Net dat in EnviDat) would be to have a harmonised format for all of stations with reusable data that it's useful and easy to use for the large majority of data consumers. Consequently, I'm thinking, in the final data to be published in EnviDat, to only have one temperature value (averaged from all others) and with a second STD_T field to document it's standard deviation (our maybe another measure of quality, but I haven't discussed this with Derek yet, since I want to let him finish the reprocessing first). 

> And we can of course also publish both variants in EnviDat, the easy reusable version and the complete one. 
Anyway, we can gladly export a second variant for you, with all temperature measurements released - do you need this now?

Derek:
> The thermocouples are at different heights, separated vertically by 1m. They are not intended to be averaged as they contain independent information. 
> Only one station, east grip, has 1 thermocouple instead of 2. We should also be careful averaging CS500 temperatures with thermocouple temperatures. The CS500 do not work below -40. 
`

**Comment by BaptisteVandecrux** [comment] 2020-10-01 11:39
> not all GC-Net stations have four temperature measurements

The standard design for the GC-Net station is to have four temperature measurements. East GRIP is the exception.

>  in the final data to be published in EnviDat, to only have one temperature value (averaged from all others) and with a second STD_T field to document it's standard deviation 

I do not find this solution attractive because, as Derek reminds us, the four temperature measurements are taken at two different levels and by two types of sensor that each have their strength, weakness and operating range. An average of these four measurements would be very hard to use.

I suggest that all four measurements are released with their respective height above the surface.

**Comment by iosifescu** [comment] 2020-10-05 14:30
Quick question: we also have the T_min and T_max from the logger, for each sensor (as T holds the temperature as averaged by the logger, but before discarding the other values, it updates the T_min and T_max). Would you need these values in the final data? Or are they quite useless for an easy reusable dataset?

**Comment by iosifescu** [comment] 2020-10-05 14:55
> I do not find this solution attractive because, as Derek reminds us, the four temperature measurements are taken at two different levels and by two types of sensor that each have their strength, weakness and operating range. An average of these four measurements would be very hard to use.
> 
> I suggest that all four measurements are released with their respective height above the surface.

OK - my mistake about suggesting an averaging, as I didn't know the details about their locations and characteristics (for me it made sense to average them to what I thought it would be the most statistically "correct" value - this is obviously not the case). However, it might make the dataset more reusable, if all temperatures are corrected to the same elevation, because I'm not sure that the majority of data users will care to read more infos about the sensors. 

Anyway, as a computer scientist and not a meteo expert, may I ask a really dumm question: Does the elevation difference of 1m matters so much? Isn't the slight error of 0.0065 °C (introduced by the 1m elevation difference) being "swallowed" by the measurement sensor error? What is the sensor precision anyway? 
Anyway, after Derek's additional information, we shouldn't average all temperatures. And I would suggest to remove/delete any erroneous values received from CS500 when the other sensors report temperatures below -40. But maybe it still makes sense to average the two thermocouples separately and the two CS500 separately (where possible), and releasing two temperatures (in order to make the data more user friendly, more easily reusable for the majority of researchers).

What do you think? (Of course, the original raw log files with unprocessed data, containing all details and explanations can also be released - so people that want to do the processing themselves can gladly do so. But as mentioned before, my main concern is to have an easily reusable dataset in EnviDat.)

**Comment by BaptisteVandecrux** [comment] 2020-10-05 16:11
> Quick question: we also have the T_min and T_max from the logger, for each sensor (as T holds the temperature as averaged by the logger, but before discarding the other values, it updates the T_min and T_max). Would you need these values in the final data? Or are they quite useless for an easy reusable dataset?

Thanks for asking.
Although I am not using them personally I believe that they should also be given in the final dataset. Future statistical analysis may be able to use these min/max measurements in ways that we cannot imagine now.

> Does the elevation difference of 1m matters so much? 

In polar or snow-covered regions, low solar radiation, high reflectivity of the snow and surface heat loss from thermal radiation brings the surface to a temperature that is several degrees lower than the air temperature. This is called a temperature inversion and it creates strong (several degrees), near-surface temperature gradients. 

![image](https://user-images.githubusercontent.com/35140661/95101870-f8459100-0732-11eb-847f-4eea0b6cbdb8.png)
from  Summit station https://dx.doi.org/10.1127/0941-2948/2008/0327

As a result the temperature measurements are very dependant on the height at which they are measured.
They can be brought to a standardized height using assumption about how the temperature profile looks like. And of course the near-surface temperature profile is very variable in time and space.

The same goes for wind speed and relative humidity measurements.

> Isn't the slight error of 0.0065 °C (introduced by the 1m elevation difference) being "swallowed" by the measurement sensor error? What is the sensor precision anyway?

Officially the sensor accuracy is 0.1degC. 
You can check [here](https://github.com/BaptisteVandecrux/GC-Net-evaluation) when the two levels of GC-Net stations are compared to the same PROMICE dataset (only one level there). It usually results in a ~0.1-0.2 degC average difference between levels, potentially more pronounced during specific periods. So yes, the difference of height between levels is creating a bias that is greater than the sensor's accuracy.

> But maybe it still makes sense to average the two thermocouples separately and the two CS500 separately (where possible), and releasing two temperatures (in order to make the data more user friendly, more easily reusable for the majority of researchers).

There is one thermocouple and one CS500 on each level. You can provide two  level-averaged temperatures but, as Derek mentioned, it would then consist of an average of two measurements >-40degC and the single thermocouple measurement when <-40degC.


I would like to stress that fewer fields do not make a better dataset. I think that each measurement has its own value and should not be merged with other measurements. Better metadata, however, greatly ease the use of a dataset, so that would be the way to go to make the data easily reusable.

**Comment by iosifescu** [comment] 2020-10-05 16:29
Thank you for the explanations, much appreciated! Based on the new information that you provided me, I now completely agree with your assessment.

**Comment by iosifescu** [comment] 2020-10-05 19:42
Actually, after all your explanations, I'm wondering about something. 

Koni and Derek had to lower the height of the sensors masts a few times over the years (as well as of the swiss camp). Derek can you confirm?

Derek has the mast/sensors height adjustments, and he will apply these adjustments. But how can someone correct the variations of the temperature measurements caused by the variation of the sensor height above ground? Because during the year the elevation above ground was constantly modified due to the snow melting... But I assume that you also had this problem with the PROMICE stations - how have you dealt with it? Would you assume a linear interpolation, or a polynomial that is considering the accelerated snow melt in summer?

**Comment by BaptisteVandecrux** [comment] 2020-10-05 20:44
Indeed best practice is to measure weather variable at a constant height over the surface but weather stations on glaciers need to be shifted up or down as the surface is melting or the snow accumulating.

At PROMICE stations, we only provide the temperature and the height at which it is measured.
The temperature at 2 m height can be calculated using the available temperature, the measured surface temperature (from upward longwave radiation sensor) and wind speed information to account for the near-surface temperature gradient and the shape of the temperature profile.
At GC-Net stations, the two measurement levels can allow interpolation of the 2 m temperature when located between the two measurements levels. Extrapolation is rather risky because very sensitive to noise and due to the non-linearity of the temperature profile close to the surface. 

I completely agree that estimations of weather variables at standard height would be easier to use.
However they require models/assumptions of the near-surface atmosphere and can be considered as level 2 products.
I have myself set up such model for [nine GC-Net stations](https://doi.org/10.18739/A24B2X56X) and know very well how tricky they can be. We also see that there are more obvious malfunctions in the dataset that need to be fixed before diving into near-surface atmospheric modelling.

Providing cleaned weather variables along with their respective measurement heights would be already a great achievement!

**Comment by iosifescu** [comment] 2020-10-06 20:43
Agree - all temperatures will be released.

**Closed as completed** 2020-10-06 20:44 UTC
